version: '3.6'
services:
  metadata-1:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_PASSWORD: postgrespassword
  metadata-2:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_PASSWORD: postgrespassword
  metadata-3:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_PASSWORD: postgrespassword
  graphql-engine-1:
    image: hasura/graphql-engine:latest
    ports:
      - "8081:8080"
    depends_on:
      - "postgres"
    restart: always
    environment:
      PG_DATABASE_URL: postgres://${PGUSER}:${PGPASSWORD}@${PGHOST}:${PGPORT}/${PGDATABASE}
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://postgres:postgrespassword@metadata-1:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
  graphql-engine-2:
    image: hasura/graphql-engine:latest
    ports:
      - "8081:8080"
    depends_on:
      - "postgres"
    restart: always
    environment:
      PG_DATABASE_URL: postgres://${PGUSER}:${PGPASSWORD}@${PGHOST}:${PGPORT}/${PGDATABASE}
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://postgres:postgrespassword@metadata-2:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
  graphql-engine-3:
    image: hasura/graphql-engine:latest
    ports:
      - "8081:8080"
    depends_on:
      - "postgres"
    restart: always
    environment:
      PG_DATABASE_URL: postgres://${PGUSER}:${PGPASSWORD}@${PGHOST}:${PGPORT}/${PGDATABASE}
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://postgres:postgrespassword@metadata-3:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
