version: '3.6'
services:
  metadata-1:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_PASSWORD: postgrespassword
  metadata-2:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_PASSWORD: postgrespassword
  metadata-3:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_PASSWORD: postgrespassword
  metadata-4:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_PASSWORD: postgrespassword
  metadata-5:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_PASSWORD: postgrespassword
  graphql-engine-1:
    image: hasura/graphql-engine:latest
    ports:
      - "8081:8080"
    depends_on:
      - "metadata-1"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@metadata-1:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
  graphql-engine-2:
    image: hasura/graphql-engine:latest
    ports:
      - "8082:8080"
    depends_on:
      - "metadata-2"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@metadata-2:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
  graphql-engine-3:
    image: hasura/graphql-engine:latest
    ports:
      - "8083:8080"
    depends_on:
      - "metadata-3"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@metadata-3:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
  graphql-engine-4:
    image: hasura/graphql-engine:latest
    ports:
      - "8084:8080"
    depends_on:
      - "metadata-4"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@metadata-4:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
  graphql-engine-5:
    image: hasura/graphql-engine:latest
    ports:
      - "8085:8080"
    depends_on:
      - "metadata-5"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@metadata-5:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
