-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- drop table if exists account cascade;
--
-- drop table if exists "order" cascade;
--
-- drop table if exists order_detail cascade;
--
-- drop table if exists product cascade;
--
-- drop table if exists region cascade;
