-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- insert into product (id, name)
-- select generate_series(1, 1000), md5(random()::text);
